# This is a basic workflow to help you get started with Actions

name: CI Check in

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-in:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run Script
        env:
          netid: ${{ secrets.netid }}
          password: ${{ secrets.password }}
        run: pipenv run python main.py
